// @ts-nocheck
/**
 * Grimoire — GitHub Gist Sharing
 *
 * Pushes the exported markdown (and optionally .grimoire.json) to a GitHub Gist.
 * Returns a shareable URL that renders beautifully on GitHub.
 *
 * Architecture decision: Uses VS Code's built-in GitHub authentication provider
 * (`vscode.authentication.getSession('github', ['gist'])`) instead of the Pro
 * backend's OAuth token. This means:
 *   - Free users can share Gists too (no Pro subscription required)
 *   - We don't need to modify the Pro OAuth scope (currently read:user only)
 *   - VS Code handles token storage, refresh, and consent UI
 *   - User sees the standard "Sign in to GitHub" flow if not authenticated
 *
 * Trade-off: This creates a dependency on VS Code's auth infrastructure.
 * If we ever need Gist support from the CLI tool, we'd need a separate
 * GitHub token flow. Acceptable for now — CLI sharing can use local export.
 *
 * GitHub Gist API docs: https://docs.github.com/en/rest/gists/gists#create-a-gist
 *
 * SECURITY notes:
 *   - Token never leaves VS Code's SecretStorage → memory → HTTPS request
 *   - We request minimal scope: just 'gist' (can't access repos, orgs, etc.)
 *   - Gists default to secret (unlisted) — accessible by URL but not indexed
 *   - OWASP: Token handling follows A07:2021 (Authentication Failures) guidance
 */

const vscode = require('vscode');

/**
 * Request a GitHub authentication session with 'gist' scope.
 * VS Code will prompt the user to sign in if no session exists.
 *
 * @param {boolean} [silent=false] - If true, don't prompt (return null if no session)
 * @returns {Promise<import('vscode').AuthenticationSession|null>}
 */
async function getGitHubSession(silent = false) {
  try {
    const session = await vscode.authentication.getSession('github', ['gist'], {
      createIfNone: !silent,
    });
    return session;
  } catch (err) {
    // User cancelled the auth prompt
    if (err.message?.includes('cancelled') || err.message?.includes('denied')) {
      return null;
    }
    throw err;
  }
}

/**
 * Create a GitHub Gist with the given files.
 *
 * @param {Object} options
 * @param {string} options.markdown - The markdown content to share
 * @param {string} [options.json] - Optional .grimoire.json content to include
 * @param {string} [options.projectName='grimoire-map'] - Used in filenames and description
 * @param {boolean} [options.isPublic=false] - Public gists are searchable; secret ones are unlisted
 * @returns {Promise<{ url: string, id: string }>} The Gist URL and ID
 * @throws {Error} If authentication fails or the API request fails
 */
async function createGist({ markdown, json = null, projectName = 'grimoire-map', isPublic = false }) {
  // ── Get GitHub token ──
  const session = await getGitHubSession();
  if (!session) {
    throw new Error('GitHub authentication was cancelled. Sign in to share Gists.');
  }

  // ── Build Gist payload ──
  // Primary file is the markdown (renders nicely on GitHub).
  // Optionally include the raw JSON for machine consumption.
  const files = {
    [`${projectName}.md`]: {
      content: markdown,
    },
  };

  if (json) {
    files[`${projectName}.grimoire.json`] = {
      content: json,
    };
  }

  const payload = {
    description: `${projectName} — Codebase map generated by Grimoire`,
    public: isPublic,
    files,
  };

  // ── Call GitHub API ──
  // POST /gists creates a new gist; returns the full gist object with html_url.
  // Rate limit: 5000 requests/hour for authenticated users — more than enough.
  const response = await fetch('https://api.github.com/gists', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${session.accessToken}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'Grimoire-VSCode-Extension',
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    console.error('[GIST] API error:', response.status, errorBody);

    // Provide actionable error messages
    if (response.status === 401) {
      throw new Error('GitHub authentication expired. Please sign in again.');
    }
    if (response.status === 403) {
      throw new Error('GitHub rate limit exceeded or token lacks "gist" scope. Try again later.');
    }
    if (response.status === 422) {
      throw new Error('Invalid gist content. The markdown may contain unsupported characters.');
    }
    throw new Error(`GitHub API returned ${response.status}: ${errorBody.slice(0, 200)}`);
  }

  const gist = await response.json();

  return {
    url: gist.html_url,
    id: gist.id,
  };
}

/**
 * Update an existing Gist (for re-sharing after re-scanning).
 * Useful for maintaining a stable share URL that always reflects the latest scan.
 *
 * @param {string} gistId - The existing Gist ID
 * @param {Object} options - Same as createGist options (minus isPublic)
 * @returns {Promise<{ url: string, id: string }>}
 */
async function updateGist(gistId, { markdown, json = null, projectName = 'grimoire-map' }) {
  const session = await getGitHubSession();
  if (!session) {
    throw new Error('GitHub authentication was cancelled.');
  }

  const files = {
    [`${projectName}.md`]: { content: markdown },
  };

  if (json) {
    files[`${projectName}.grimoire.json`] = { content: json };
  }

  const response = await fetch(`https://api.github.com/gists/${gistId}`, {
    method: 'PATCH',
    headers: {
      Authorization: `Bearer ${session.accessToken}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'Grimoire-VSCode-Extension',
    },
    body: JSON.stringify({
      description: `${projectName} — Codebase map generated by Grimoire`,
      files,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Failed to update Gist: ${response.status} ${errorBody.slice(0, 200)}`);
  }

  const gist = await response.json();
  return { url: gist.html_url, id: gist.id };
}

module.exports = { createGist, updateGist, getGitHubSession };
