// @ts-nocheck
/**
 * Grimoire — Markdown Exporter
 *
 * Converts a .grimoire.json tree into a clean, human-readable markdown file.
 * Designed for sharing via GitHub Gist, README inserts, or standalone docs.
 *
 * Architecture decision: Pure function with no VS Code dependencies.
 * This keeps it testable and reusable from the CLI tool (grimoire.py) if
 * we ever want to add markdown export there too.
 *
 * Trade-off: We generate the full tree in one pass rather than streaming.
 * For repos under ~5000 files this is fine; if we ever hit perf issues,
 * we'd switch to a generator/stream approach.
 */

/**
 * Convert a .grimoire.json data object into a formatted markdown string.
 *
 * @param {Object} data - The parsed .grimoire.json content
 * @param {Object} data.tree - Root tree node with name, description, children[], files[]
 * @param {Object} [data.snippets] - Optional file path → code snippet map
 * @param {boolean} [data.plainEnglish] - Whether descriptions are in plain English mode
 * @param {string} [data.model] - The AI model used for scanning
 * @param {Object} [options] - Export options
 * @param {boolean} [options.includeTags=true] - Include tag badges after file names
 * @param {boolean} [options.includeSnippets=false] - Include code snippets (makes output much longer)
 * @param {boolean} [options.includeMetadata=true] - Include footer with scan metadata
 * @param {string} [options.projectName] - Override the root folder name in the title
 * @returns {string} The complete markdown document
 */
function exportToMarkdown(data, options = {}) {
  const {
    includeTags = true,
    includeSnippets = false,
    includeMetadata = true,
    projectName = null,
  } = options;

  const tree = data.tree;
  if (!tree) {
    return '# Grimoire Map\n\n_No scan data available. Run `Grimoire: Scan Workspace` first._\n';
  }

  const lines = [];
  const rootName = projectName || tree.name || 'Project';

  // ── Header ──
  lines.push(`# ${rootName}`);
  lines.push('');
  if (tree.description) {
    lines.push(`> ${tree.description}`);
    lines.push('');
  }

  // ── Stats summary ──
  const stats = computeStats(tree);
  lines.push(`**${stats.totalFiles}** files across **${stats.totalDirs}** directories`);
  if (stats.tagCounts.size > 0) {
    const topTags = [...stats.tagCounts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 8)
      .map(([tag, count]) => `\`${tag}\` (${count})`)
      .join(' · ');
    lines.push(`Top tags: ${topTags}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Directory tree ──
  lines.push('## Directory Structure');
  lines.push('');
  lines.push('```');
  renderAsciiTree(tree, '', true, lines);
  lines.push('```');
  lines.push('');

  // ── Detailed file descriptions ──
  lines.push('## File Descriptions');
  lines.push('');
  renderDescriptions(tree, '', lines, { includeTags, includeSnippets, snippets: data.snippets || {} });

  // ── Metadata footer ──
  if (includeMetadata) {
    lines.push('---');
    lines.push('');
    lines.push(`*Generated by [Grimoire](https://marketplace.visualstudio.com/items?itemName=kaden-g.grimoire-ai)*`);
    const parts = [];
    if (data.model) parts.push(`Model: \`${data.model}\``);
    if (data.plainEnglish !== undefined) parts.push(`Mode: ${data.plainEnglish ? 'Plain English' : 'Technical'}`);
    parts.push(`Date: ${new Date().toISOString().split('T')[0]}`);
    lines.push(`*${parts.join(' · ')}*`);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Render an ASCII directory tree (like the `tree` command).
 * Preserves repo order — children and files appear in the order
 * they were scanned, NOT alphabetically sorted.
 *
 * @param {Object} node - Tree node
 * @param {string} prefix - Current indentation prefix
 * @param {boolean} isRoot - Whether this is the root node
 * @param {string[]} lines - Output accumulator
 */
function renderAsciiTree(node, prefix, isRoot, lines) {
  if (isRoot) {
    lines.push(`${node.name}/`);
  }

  // Collect all children: directories first, then files (matching typical tree output)
  const dirs = node.children || [];
  const files = node.files || [];
  const allEntries = [
    ...dirs.map(d => ({ type: 'dir', item: d })),
    ...files.map(f => ({ type: 'file', item: f })),
  ];

  allEntries.forEach((entry, i) => {
    const isLast = i === allEntries.length - 1;
    const connector = isLast ? '└── ' : '├── ';
    const childPrefix = isLast ? '    ' : '│   ';

    if (entry.type === 'dir') {
      lines.push(`${prefix}${connector}${entry.item.name}/`);
      renderAsciiTree(entry.item, prefix + childPrefix, false, lines);
    } else {
      lines.push(`${prefix}${connector}${entry.item.name}`);
    }
  });
}

/**
 * Render detailed file/directory descriptions in a readable format.
 * Uses H3 for directories and bullet lists for files within each.
 *
 * @param {Object} node - Tree node
 * @param {string} currentPath - Accumulated path for context
 * @param {string[]} lines - Output accumulator
 * @param {Object} opts - Options (includeTags, includeSnippets, snippets)
 */
function renderDescriptions(node, currentPath, lines, opts) {
  const dirs = node.children || [];
  const files = node.files || [];
  const dirPath = currentPath ? `${currentPath}/${node.name}` : node.name;

  // Render files in this directory
  if (files.length > 0) {
    lines.push(`### ${dirPath || '/'}`);
    if (node.description) {
      lines.push(`> ${node.description}`);
    }
    lines.push('');

    files.forEach(file => {
      const tagStr = (opts.includeTags && file.tags && file.tags.length > 0)
        ? ' ' + file.tags.map(t => `\`${t}\``).join(' ')
        : '';

      // File name + purpose on one line, tags inline
      lines.push(`- **${file.name}**${tagStr}`);
      if (file.purpose) {
        lines.push(`  ${file.purpose}`);
      }

      // Optional code snippet
      if (opts.includeSnippets) {
        const snippetKey = Object.keys(opts.snippets).find(k => k.endsWith(file.name));
        if (snippetKey && opts.snippets[snippetKey]) {
          lines.push('');
          lines.push('  <details><summary>Preview</summary>');
          lines.push('');
          lines.push('  ```');
          // Trim to first 20 lines to keep it manageable
          const snippetLines = opts.snippets[snippetKey].split('\n').slice(0, 20);
          snippetLines.forEach(sl => lines.push(`  ${sl}`));
          if (opts.snippets[snippetKey].split('\n').length > 20) {
            lines.push('  // ...');
          }
          lines.push('  ```');
          lines.push('');
          lines.push('  </details>');
        }
      }
      lines.push('');
    });
  }

  // Recurse into subdirectories
  dirs.forEach(dir => {
    renderDescriptions(dir, dirPath, lines, opts);
  });
}

/**
 * Walk the tree and compute aggregate stats.
 *
 * @param {Object} node - Tree node
 * @returns {{ totalFiles: number, totalDirs: number, tagCounts: Map<string, number> }}
 */
function computeStats(node) {
  let totalFiles = 0;
  let totalDirs = 0;
  const tagCounts = new Map();

  function walk(n) {
    const dirs = n.children || [];
    const files = n.files || [];

    totalDirs += dirs.length;
    totalFiles += files.length;

    files.forEach(f => {
      (f.tags || []).forEach(tag => {
        tagCounts.set(tag, (tagCounts.get(tag) || 0) + 1);
      });
    });

    dirs.forEach(d => walk(d));
  }

  walk(node);
  return { totalFiles, totalDirs, tagCounts };
}

module.exports = { exportToMarkdown, computeStats };
